edition = "2021"
style_edition = "2024"

# Formatting options
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Default"

# Import formatting
imports_granularity = "Crate"
imports_layout = "Mixed"
group_imports = "StdExternalCrate"

# Function formatting
fn_single_line = false
where_single_line = false
force_explicit_abi = true

# Control flow formatting
control_brace_style = "AlwaysSameLine"
brace_style = "SameLineWhere"

# Comment formatting
normalize_comments = true
wrap_comments = true
comment_width = 80
normalize_doc_attributes = true

# String formatting
format_strings = true

# Misc formatting
format_code_in_doc_comments = true
format_macro_matchers = true
hex_literal_case = "Lower"
use_field_init_shorthand = true
use_try_shorthand = true
force_multiline_blocks = false
reorder_impl_items = true